FROM node:latest AS builder

# set working directory
WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm ci

# copy source & build
COPY . .
RUN npm run build

FROM nginx:stable-alpine

# remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# copy built assets from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]
